import { useEffect, useRef } from "react";
import { useMockCall } from "../../hooks/useMockCall";
import type { PrototypeCallInterruption, PrototypeCallState } from "../../types/call";
import type { CallTask, TransportRequest } from "../../types/transport";
import { SignalOrb } from "../SignalOrb/SignalOrb";
import "./CallOverlay.css";
type Props = { request: TransportRequest; task: CallTask; onClose: () => void; onReturnHome: () => void; onViewReport: () => void };
const stageCopy: Partial<Record<PrototypeCallState, string>> = { preparing: "Preparing customer follow-up", dialing: "Dialing customer", ringing: "Phone ringing", connected: "Connection established", conversation: "Coordination conversation in progress", processing: "Processing structured outcome", complete: "Call outcome ready" };
const interruptions: Record<PrototypeCallInterruption, { title: string; message: string }> = { cancelled: { title: "Conversation cancelled", message: "No call outcome was generated." }, "no-answer": { title: "No answer", message: "The fictional recipient did not answer during this prototype state." }, failed: { title: "Call failed", message: "The prototype call monitor could not continue." }, "processing-failed": { title: "Outcome processing failed", message: "The fictional structured outcome could not be prepared." } };
export function CallOverlay({ request, task, onClose, onReturnHome, onViewReport }: Props) { const call = useMockCall(); const headingRef = useRef<HTMLHeadingElement>(null); const openerRef = useRef<HTMLElement | null>(null); const dialogRef = useRef<HTMLDivElement>(null); const active = ["preparing", "dialing", "ringing", "connected", "conversation", "processing"].includes(call.state); const topic = task.topics[Math.min(Math.floor(call.duration / 8), task.topics.length - 1)]; const interruption = isInterruption(call.state) ? interruptions[call.state] : null;
useEffect(() => { openerRef.current = document.activeElement instanceof HTMLElement ? document.activeElement : null; return () => openerRef.current?.focus(); }, []); useEffect(() => { headingRef.current?.focus(); }, [call.state]); useEffect(() => { const handler = (event: KeyboardEvent) => { if (event.key === "Escape" && !active) onClose(); if (event.key !== "Tab" || !dialogRef.current) return; const items = dialogRef.current.querySelectorAll<HTMLElement>("button:not([disabled]), [href], [tabindex]:not([tabindex='-1'])"); const first = items[0], last = items[items.length - 1]; if (!first || !last) return; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, [active, onClose]);
return <div className="call-overlay-backdrop"><section className="call-overlay" role="dialog" aria-modal="true" aria-labelledby="call-overlay-title" ref={dialogRef}><header className="call-overlay__top"><div><p className="eyebrow">CALL-E coordination monitor</p><span className="call-overlay__prototype">PROTOTYPE MONITOR · NO LIVE BROWSER AUDIO</span></div>{!active && <button className="overlay-close" onClick={onClose}>Close</button>}</header>{interruption ? <InterruptionPanel {...interruption} onRetry={call.retry} onClose={onClose} onHome={onReturnHome} /> : <><div className="call-overlay__shipment"><div><small>Transport reference</small><strong>{request.reference}</strong></div><div><small>Calling</small><span>{task.recipient.fullName}</span></div><div><small>Role / purpose</small><span>{task.recipientRole.replace("_", " ")} · {task.type.replace("-", " ")}</span></div><div><small>Vehicle / route</small><span>{request.vehicle.year} {request.vehicle.make} {request.vehicle.model} · {request.pickup.address} → {request.delivery.address}</span></div></div><main className="call-overlay__monitor"><SignalOrb state={call.state} /><div className="call-overlay__status"><p className="meta-label" aria-live="polite">Current call stage</p><h2 id="call-overlay-title" ref={headingRef} tabIndex={-1}>{stageCopy[call.state]}</h2><p className="call-overlay__scenario">{task.goal}</p>{["connected", "conversation", "processing", "complete"].includes(call.state) && <time className="call-overlay__timer" aria-label={`Elapsed call duration ${formatDuration(call.duration)}`}>{formatDuration(call.duration)}</time>}{call.state === "conversation" && <><p className="call-overlay__review"><span>Current topic</span>{topic}</p><p className="call-overlay__guidance">Continue the coordination conversation. This console will prepare a structured call outcome when it ends.</p></>}{call.state === "processing" && <p className="call-overlay__guidance">Preparing a fictional structured outcome.</p>}{call.state === "complete" && <p className="call-overlay__guidance">Prototype conversation complete. The call outcome is ready to review.</p>}<p className="prototype-notice">This visual monitor does not represent live browser audio.</p></div></main><footer className="call-overlay__controls">{call.state === "conversation" && <><button className="button button--primary" onClick={call.completeConversation}>Complete mock conversation</button><button className="button button--quiet" onClick={call.cancel}>Cancel conversation</button></>}{call.state === "processing" && <button className="button button--primary" disabled>Processing outcome…</button>}{call.state === "complete" && <><button className="button button--primary" onClick={onViewReport}>View call outcome</button><button className="button button--quiet" onClick={onReturnHome}>Return to transport queue</button></>}</footer></>}</section></div>; }
function InterruptionPanel({ title, message, onRetry, onClose, onHome }: { title: string; message: string; onRetry: () => void; onClose: () => void; onHome: () => void }) { return <main className="call-overlay__interruption"><p className="meta-label">Prototype interruption</p><h2 id="call-overlay-title" tabIndex={-1}>{title}</h2><p>{message}</p><div className="form-actions"><button className="button button--primary" onClick={onRetry}>Try again</button><button className="button button--quiet" onClick={onClose}>Return to call brief</button><button className="button button--quiet" onClick={onHome}>Return to transport queue</button></div></main>; }
function isInterruption(state: PrototypeCallState): state is PrototypeCallInterruption { return ["cancelled", "no-answer", "failed", "processing-failed"].includes(state); }
function formatDuration(seconds: number) { return [Math.floor(seconds / 3600), Math.floor((seconds % 3600) / 60), seconds % 60].map((value) => String(value).padStart(2, "0")).join(":"); }
